Repository AY2324S2-CS2103-T14-1/tp, pull requests merged in 2024-04, with the labels that each got.

#140 Update Ui and help Window
  docs/images/Ui.png
  docs/images/helpMessage.png
Labels: documentation

#138 Remove Link Command from UG, fix typos
  docs/UserGuide.md
Labels: documentation

#143 Update DG for Timetable and finding slots feature
  docs/DeveloperGuide.md
  docs/diagrams/FindingAvailableSlotsSequenceDiagram.puml
Labels: documentation

#136 Add copy command
  .gitignore
  .vscode/settings.json
  src/main/java/educonnect/logic/Messages.java
  src/main/java/educonnect/logic/commands/AddCommand.java
  src/main/java/educonnect/logic/commands/CopyCommand.java
  src/main/java/educonnect/logic/commands/ExitCommand.java
  src/main/java/educonnect/logic/commands/ListCommand.java
  src/main/java/educonnect/logic/parser/AddCommandParser.java
  src/main/java/educonnect/logic/parser/AddressBookParser.java
  src/main/java/educonnect/logic/parser/ArgumentMultimap.java
  src/main/java/educonnect/logic/parser/CopyCommandParser.java
  src/main/java/educonnect/logic/parser/FindCommandParser.java
  src/main/java/educonnect/model/student/predicates/TagContainsKeywordsPredicate.java
  src/main/java/educonnect/model/student/timetable/Day.java
  src/main/java/educonnect/model/student/timetable/Period.java
  src/main/java/educonnect/ui/MainWindow.java
  src/main/java/educonnect/ui/StudentListPanel.java
  src/test/data/JsonSerializableAddressBookTest/typicalStudentsAddressBook.json
  src/test/java/educonnect/logic/commands/CopyCommandTest.java
  src/test/java/educonnect/logic/commands/DeleteCommandTest.java
  src/test/java/educonnect/logic/commands/EditCommandTest.java
  src/test/java/educonnect/logic/commands/EditStudentDescriptorTest.java
  src/test/java/educonnect/logic/parser/AddCommandParserTest.java
  src/test/java/educonnect/logic/parser/CopyCommandParserTest.java
  src/test/java/educonnect/storage/JsonAdaptedStudentTest.java
  src/test/java/educonnect/testutil/TypicalStudents.java
Labels: enhancement

#141 Update UI settings for v1.3b
  src/main/java/educonnect/MainApp.java
  src/main/java/educonnect/ui/MainWindow.java
Labels: enhancement

#135 Add finding common slots functionality
  src/main/java/educonnect/logic/commands/SlotsCommand.java
  src/main/java/educonnect/logic/parser/AddressBookParser.java
  src/main/java/educonnect/logic/parser/CliSyntax.java
  src/main/java/educonnect/logic/parser/ParserUtil.java
  src/main/java/educonnect/logic/parser/SlotsCommandParser.java
  src/main/java/educonnect/model/Model.java
  src/main/java/educonnect/model/ModelManager.java
  src/main/java/educonnect/model/student/timetable/AvailableSlots.java
  src/main/java/educonnect/model/student/timetable/Day.java
  src/main/java/educonnect/model/student/timetable/Period.java
  src/main/java/educonnect/model/student/timetable/Timetable.java
  src/main/java/educonnect/model/student/timetable/exceptions/InvalidDurationException.java
  src/main/java/educonnect/model/util/SampleDataUtil.java
  src/test/data/JsonSerializableAddressBookTest/typicalStudentsAddressBook.json
  src/test/java/educonnect/logic/commands/AddCommandTest.java
  src/test/java/educonnect/logic/commands/EditCommandTest.java
  src/test/java/educonnect/logic/commands/SlotsCommandTest.java
  src/test/java/educonnect/logic/parser/AddressBookParserTest.java
  src/test/java/educonnect/logic/parser/ParserUtilTest.java
  src/test/java/educonnect/logic/parser/SlotsCommandParserTest.java
  src/test/java/educonnect/model/student/timetable/AvailableSlotsTest.java
  src/test/java/educonnect/model/student/timetable/DayTest.java
  src/test/java/educonnect/model/student/timetable/PeriodTest.java
  src/test/java/educonnect/model/student/timetable/TimetableTest.java
  src/test/java/educonnect/testutil/TypicalStudents.java
  src/test/java/educonnect/testutil/TypicalTimetableAndValues.java
Labels: enhancement, must-have

#149 Update list command to save the show timetable option
  README.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddSequenceDiagram.puml
  docs/diagrams/ListSequenceDiagram.puml
  docs/images/sampleUI.png
  docs/index.md
  src/main/java/educonnect/logic/Logic.java
  src/main/java/educonnect/logic/LogicManager.java
  src/main/java/educonnect/logic/commands/CommandResult.java
  src/main/java/educonnect/logic/commands/EditCommand.java
  src/main/java/educonnect/logic/commands/ExitCommand.java
  src/main/java/educonnect/logic/commands/HelpCommand.java
  src/main/java/educonnect/logic/commands/ListCommand.java
  src/main/java/educonnect/model/Model.java
  src/main/java/educonnect/model/ModelManager.java
  src/main/java/educonnect/model/ReadOnlyUserPrefs.java
  src/main/java/educonnect/model/UserPrefs.java
  src/main/java/educonnect/ui/MainWindow.java
  src/test/java/educonnect/logic/commands/AddCommandTest.java
  src/test/java/educonnect/logic/commands/CommandResultTest.java
  src/test/java/educonnect/logic/commands/CopyCommandTest.java
  src/test/java/educonnect/logic/commands/ExitCommandTest.java
  src/test/java/educonnect/logic/commands/HelpCommandTest.java
  src/test/java/educonnect/model/ModelManagerTest.java
  src/test/java/educonnect/model/UserPrefsTest.java
Labels: enhancement

#156 Add clearer command message usages, no duplicate prefixes for delete and make code readable for msg usage.
  src/main/java/educonnect/logic/commands/AddCommand.java
  src/main/java/educonnect/logic/commands/DeleteCommand.java
  src/main/java/educonnect/logic/commands/EditCommand.java
  src/main/java/educonnect/logic/commands/FindCommand.java
  src/main/java/educonnect/logic/parser/AddCommandParser.java
  src/main/java/educonnect/logic/parser/DeleteCommandParser.java
  src/main/java/educonnect/logic/parser/EditCommandParser.java
Labels: code standard

#157 Two whitespace dashes
  src/main/java/educonnect/logic/parser/ParserUtil.java
  src/main/java/educonnect/model/student/Name.java
  src/main/java/educonnect/model/student/StudentId.java
  src/main/java/educonnect/model/student/predicates/NameContainsKeywordsPredicate.java
  src/test/java/educonnect/model/student/NameTest.java
  src/test/java/educonnect/model/student/StudentIdTest.java
Labels: enhancement

#142 Update UG with copy command
  README.md
  docs/UserGuide.md
  docs/images/UndoSequenceDiagram-Logic.png
  docs/images/UndoSequenceDiagram-Model.png
  docs/images/copyToGmail.png
Labels: documentation

#152 Update help command to accept parameters
  docs/UserGuide.md
  docs/images/helpAddMessage.png
  src/main/java/educonnect/logic/commands/AddCommand.java
  src/main/java/educonnect/logic/commands/ClearCommand.java
  src/main/java/educonnect/logic/commands/DeleteCommand.java
  src/main/java/educonnect/logic/commands/EditCommand.java
  src/main/java/educonnect/logic/commands/FindCommand.java
  src/main/java/educonnect/logic/commands/HelpCommand.java
  src/main/java/educonnect/logic/parser/AddressBookParser.java
  src/main/java/educonnect/logic/parser/HelpCommandParser.java
  src/main/java/educonnect/logic/parser/ParserUtil.java
  src/main/java/educonnect/model/student/Link.java
  src/test/java/educonnect/logic/commands/CommandTestUtil.java
  src/test/java/educonnect/logic/commands/HelpCommandTest.java
  src/test/java/educonnect/logic/parser/AddCommandParserTest.java
  src/test/java/educonnect/logic/parser/AddressBookParserTest.java
  src/test/java/educonnect/logic/parser/EditCommandParserTest.java
  src/test/java/educonnect/logic/parser/HelpCommandParserTest.java
  src/test/java/educonnect/logic/parser/ParserUtilTest.java
Labels: enhancement

#162 Edit command unique feature
  docs/UserGuide.md
  src/main/java/educonnect/logic/commands/EditCommand.java
  src/main/java/educonnect/logic/parser/ArgumentMultimap.java
  src/main/java/educonnect/logic/parser/CliSyntax.java
  src/main/java/educonnect/logic/parser/EditCommandParser.java
  src/test/java/educonnect/logic/commands/CommandTestUtil.java
  src/test/java/educonnect/logic/commands/EditCommandTest.java
  src/test/java/educonnect/logic/parser/AddressBookParserTest.java
  src/test/java/educonnect/logic/parser/EditCommandParserTest.java
Labels: documentation, enhancement

#171 Update and fix typos in UG and DG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
Labels: documentation

#172 Update version number
  build.gradle
Labels: documentation

#253 Fix first day not captured for timetable-related commands
  src/main/java/educonnect/logic/parser/AddCommandParser.java
  src/main/java/educonnect/logic/parser/EditCommandParser.java
Labels: bug

#250 Improves grammar of messages for Timetable and SlotsCommand
  src/main/java/educonnect/logic/commands/SlotsCommand.java
  src/main/java/educonnect/model/student/timetable/Period.java
Labels: code standard

#251 Fix InvalidPeriodException not being thrown to ParseException for display
  src/main/java/educonnect/logic/parser/ParserUtil.java
Labels: bug

#252 Fix unable to parse capitalized day prefixes
  src/main/java/educonnect/logic/parser/AddCommandParser.java
  src/main/java/educonnect/logic/parser/EditCommandParser.java
  src/test/java/educonnect/logic/parser/AddCommandParserTest.java
Labels: bug, code standard

#249 Update ug ped
  docs/UserGuide.md
  src/main/java/educonnect/logic/commands/EditCommand.java
Labels: documentation

#255 Add clarification for slots and corrected wrong timing
  docs/UserGuide.md
  src/main/java/educonnect/logic/commands/SlotsCommand.java
  src/main/java/educonnect/model/student/timetable/exceptions/OverlapPeriodException.java
Labels: documentation

#256 Fix empty argument error for find command
  src/main/java/educonnect/logic/Messages.java
  src/main/java/educonnect/logic/commands/FindCommand.java
  src/main/java/educonnect/logic/parser/FindCommandParser.java
  src/main/java/educonnect/model/student/predicates/EmailContainsKeywordsPredicate.java
  src/main/java/educonnect/model/student/predicates/IdContainsKeywordsPredicate.java
  src/main/java/educonnect/model/student/predicates/NameContainsKeywordsPredicate.java
  src/main/java/educonnect/model/student/predicates/TelegramContainsKeywordsPredicate.java
  src/test/java/educonnect/logic/commands/CommandTestUtil.java
  src/test/java/educonnect/logic/parser/FindCommandParserTest.java
Labels: bug

#259 Fix edit command unique identifier bug
  src/main/java/educonnect/logic/parser/EditCommandParser.java
  src/main/java/educonnect/model/student/predicates/EmailMatchesKeywordsPredicate.java
  src/main/java/educonnect/model/student/predicates/IdMatchesKeywordsPredicate.java
  src/main/java/educonnect/model/student/predicates/TelegramMatchesKeywordsPredicate.java
  src/test/java/educonnect/logic/parser/EditCommandParserTest.java
Labels: bug

#264 Add Known Issues to UG
  docs/UserGuide.md
Labels: documentation

#266 Update wrong link in UG
  docs/UserGuide.md
Labels: documentation

#268 Branch update wrong timetable prefix error message
  src/main/java/educonnect/logic/parser/ParserUtil.java
  src/main/java/educonnect/model/student/timetable/Timetable.java
  src/test/java/educonnect/logic/parser/ParserUtilTest.java
Labels: bug

#269 Rename MD file for marclamp
  docs/AboutUs.md
  docs/team/marclamp.md
Labels: documentation

#254 Regex bugfix for link. email, and telegram
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/educonnect/logic/commands/AddCommand.java
  src/main/java/educonnect/logic/commands/EditCommand.java
  src/main/java/educonnect/logic/parser/ParserUtil.java
  src/main/java/educonnect/model/student/Link.java
  src/main/java/educonnect/model/student/TelegramHandle.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidStudentAddressBook.json
  src/test/data/JsonAddressBookStorageTest/invalidStudentAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicateEmailAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalStudentsAddressBook.json
  src/test/java/educonnect/logic/commands/CommandTestUtil.java
  src/test/java/educonnect/model/student/LinkTest.java
  src/test/java/educonnect/model/student/TelegramHandleTest.java
  src/test/java/educonnect/testutil/StudentBuilder.java
  src/test/java/educonnect/testutil/TypicalStudents.java
Labels: bug

#262 Update DG and include copy description
  build.gradle
  docs/DeveloperGuide.md
  docs/diagrams/ArchitectureSequenceDiagram.puml
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/CopySequenceDiagram.puml
  docs/diagrams/EditSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  src/main/java/educonnect/MainApp.java
  src/main/java/educonnect/logic/parser/EditCommandParser.java
Labels: documentation

#272 Fix format error
  docs/UserGuide.md
Labels: documentation
