Repository AY2324S2-CS2103-T14-1/tp, pull requests merged in 2024-03, with the labels that each got.

#59 No duplicate unique identifiers for students
  src/main/java/educonnect/commons/util/StringUtil.java
  src/main/java/educonnect/logic/commands/AddCommand.java
  src/main/java/educonnect/logic/commands/EditCommand.java
  src/main/java/educonnect/model/AddressBook.java
  src/main/java/educonnect/model/Model.java
  src/main/java/educonnect/model/ModelManager.java
  src/main/java/educonnect/model/student/Student.java
  src/main/java/educonnect/model/student/UniqueStudentList.java
  src/main/java/educonnect/model/student/exceptions/DuplicateStudentException.java
  src/main/java/educonnect/model/util/SampleDataUtil.java
  src/main/java/educonnect/storage/JsonSerializableAddressBook.java
  src/test/data/JsonSerializableAddressBookTest/duplicateEmailAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicateStudentIdAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicateTelegramHandleAddressBook.json
  src/test/java/educonnect/commons/util/StringUtilTest.java
  src/test/java/educonnect/logic/commands/AddCommandIntegrationTest.java
  src/test/java/educonnect/logic/commands/AddCommandTest.java
  src/test/java/educonnect/logic/commands/EditCommandTest.java
  src/test/java/educonnect/model/AddressBookTest.java
  src/test/java/educonnect/model/ModelManagerTest.java
  src/test/java/educonnect/model/student/UniqueStudentListTest.java
  src/test/java/educonnect/storage/JsonSerializableAddressBookTest.java
  src/test/java/educonnect/testutil/StudentBuilder.java
Labels: bug

#61 Fix naming issues after transition
  src/main/java/educonnect/model/student/Student.java
  src/main/java/educonnect/model/student/StudentId.java
  src/main/java/educonnect/model/student/TelegramHandle.java
  src/main/java/educonnect/ui/StudentCard.java
  src/test/java/educonnect/logic/parser/AddCommandParserTest.java
  src/test/java/educonnect/logic/parser/EditCommandParserTest.java
  src/test/java/educonnect/model/student/TelegramHandleTest.java
Labels: documentation, code standard

#62 Fix empty cell color bug
  src/main/resources/view/Extensions.css
Labels: bug

#67 Update UserGuide - Add and Edit Command
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/findAlex.png
  docs/images/findAlexDavidResult.png
  docs/images/helpMessage.png
  src/test/java/educonnect/logic/commands/AddCommandIntegrationTest.java
Labels: documentation

#68 Update UG for find command
  docs/UserGuide.md
  docs/images/findJohn.png
Labels: documentation

#73 Update UG for delete command
  docs/UserGuide.md
  docs/images/findAndDelete.png
Labels: documentation

#75 Branch better help message
  src/main/java/educonnect/ui/HelpWindow.java
Labels: enhancement, good-to-have

#77 Update delete command in UserGuide
  docs/UserGuide.md
Labels: documentation

#80 Update AboutUs
  docs/AboutUs.md
Labels: documentation

#78 Add Timetable tracking into Student
  docs/UserGuide.md
  src/main/java/educonnect/logic/Messages.java
  src/main/java/educonnect/logic/commands/EditCommand.java
  src/main/java/educonnect/logic/parser/AddCommandParser.java
  src/main/java/educonnect/logic/parser/ArgumentTokenizer.java
  src/main/java/educonnect/logic/parser/CliSyntax.java
  src/main/java/educonnect/logic/parser/EditCommandParser.java
  src/main/java/educonnect/logic/parser/ParserUtil.java
  src/main/java/educonnect/model/student/Student.java
  src/main/java/educonnect/model/student/timetable/Day.java
  src/main/java/educonnect/model/student/timetable/Period.java
  src/main/java/educonnect/model/student/timetable/Timetable.java
  src/main/java/educonnect/model/student/timetable/exceptions/InvalidPeriodException.java
  src/main/java/educonnect/model/student/timetable/exceptions/NumberOfDaysException.java
  src/main/java/educonnect/model/student/timetable/exceptions/OverlapPeriodException.java
  src/main/java/educonnect/model/util/SampleDataUtil.java
  src/main/java/educonnect/storage/JsonAdaptedStudent.java
  src/main/java/educonnect/ui/StudentCard.java
  src/main/resources/view/StudentListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicateEmailAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicateStudentIdAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicateTelegramHandleAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/invalidStudentAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalStudentsAddressBook.json
  src/test/java/educonnect/logic/commands/CommandTestUtil.java
  src/test/java/educonnect/logic/commands/EditCommandTest.java
  src/test/java/educonnect/logic/commands/EditStudentDescriptorTest.java
  src/test/java/educonnect/logic/parser/AddCommandParserTest.java
  src/test/java/educonnect/logic/parser/AddressBookParserTest.java
  src/test/java/educonnect/logic/parser/ParserUtilTest.java
  src/test/java/educonnect/model/student/timetable/DayTest.java
  src/test/java/educonnect/model/student/timetable/PeriodTest.java
  src/test/java/educonnect/model/student/timetable/TimetableTest.java
  src/test/java/educonnect/storage/JsonAdaptedStudentTest.java
  src/test/java/educonnect/testutil/EditStudentDescriptorBuilder.java
  src/test/java/educonnect/testutil/StudentBuilder.java
  src/test/java/educonnect/testutil/StudentUtil.java
  src/test/java/educonnect/testutil/TypicalStudents.java
  src/test/java/educonnect/testutil/TypicalTimetableAndValues.java
Labels: enhancement, must-have

#87 Bug fix for SampleDataUtil typo
  src/main/java/educonnect/model/util/SampleDataUtil.java
Labels: bug

#90 Update UML diagrams and respective DG sections to match
  docs/DeveloperGuide.md
  docs/diagrams/AddSequenceDiagram.png
  docs/diagrams/AddSequenceDiagram.puml
  docs/diagrams/StudentClassDiagram.png
  docs/diagrams/StudentClassDiagram.puml
Labels: documentation

#91 Update GUI
  src/main/java/educonnect/ui/StudentCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/StudentListCard.fxml
Labels: must-have, nice-to-have

#92 Update find command for multiple filter criteria
  src/main/java/educonnect/logic/commands/EditCommand.java
  src/main/java/educonnect/logic/commands/FindCommand.java
  src/main/java/educonnect/logic/commands/LinkCommand.java
  src/main/java/educonnect/logic/parser/AddCommandParser.java
  src/main/java/educonnect/logic/parser/EditCommandParser.java
  src/main/java/educonnect/logic/parser/FindCommandParser.java
  src/main/java/educonnect/logic/parser/ParserUtil.java
  src/main/java/educonnect/model/Model.java
  src/main/java/educonnect/model/ModelManager.java
  src/main/java/educonnect/model/student/Student.java
  src/main/java/educonnect/model/student/Tag.java
  src/main/java/educonnect/model/student/predicates/EmailContainsKeywordsPredicate.java
  src/main/java/educonnect/model/student/predicates/IdContainsKeywordsPredicate.java
  src/main/java/educonnect/model/student/predicates/NameContainsKeywordsPredicate.java
  src/main/java/educonnect/model/student/predicates/TagContainsKeywordsPredicate.java
  src/main/java/educonnect/model/student/predicates/TelegramContainsKeywordsPredicate.java
  src/main/java/educonnect/model/util/SampleDataUtil.java
  src/main/java/educonnect/storage/JsonAdaptedStudent.java
  src/main/java/educonnect/storage/JsonAdaptedTag.java
  src/test/java/educonnect/logic/commands/AddCommandTest.java
  src/test/java/educonnect/logic/commands/CommandTestUtil.java
  src/test/java/educonnect/logic/commands/DeleteCommandTest.java
  src/test/java/educonnect/logic/commands/FindCommandTest.java
  src/test/java/educonnect/logic/parser/AddCommandParserTest.java
  src/test/java/educonnect/logic/parser/AddressBookParserTest.java
  src/test/java/educonnect/logic/parser/EditCommandParserTest.java
  src/test/java/educonnect/logic/parser/ParserUtilTest.java
  src/test/java/educonnect/model/ModelManagerTest.java
  src/test/java/educonnect/model/student/NameContainsKeywordsPredicateTest.java
  src/test/java/educonnect/model/student/TagTest.java
  src/test/java/educonnect/testutil/EditStudentDescriptorBuilder.java
  src/test/java/educonnect/testutil/StudentBuilder.java
  src/test/java/educonnect/testutil/StudentUtil.java
Labels: enhancement, good-to-have

#95 Update UML architecture sequence diagram
  docs/diagrams/ArchitectureSequenceDiagram.puml
Labels: documentation

#94 Fix NullPointerException when link field is missing from addressbook.json
  src/main/java/educonnect/commons/util/CollectionUtil.java
  src/main/java/educonnect/logic/Messages.java
  src/main/java/educonnect/logic/commands/EditCommand.java
  src/main/java/educonnect/logic/commands/LinkCommand.java
  src/main/java/educonnect/logic/parser/AddCommandParser.java
  src/main/java/educonnect/logic/parser/ArgumentMultimap.java
  src/main/java/educonnect/logic/parser/LinkCommandParser.java
  src/main/java/educonnect/model/student/Link.java
  src/main/java/educonnect/model/student/Student.java
  src/main/java/educonnect/model/student/timetable/Timetable.java
  src/main/java/educonnect/storage/JsonAdaptedStudent.java
  src/main/java/educonnect/ui/StudentCard.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/StudentListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/typicalStudentsAddressBook.json
  src/test/java/educonnect/logic/LogicManagerTest.java
  src/test/java/educonnect/logic/commands/CommandTestUtil.java
  src/test/java/educonnect/logic/commands/EditCommandTest.java
  src/test/java/educonnect/logic/commands/LinkCommandTest.java
  src/test/java/educonnect/logic/parser/AddCommandParserTest.java
  src/test/java/educonnect/logic/parser/AddressBookParserTest.java
  src/test/java/educonnect/logic/parser/LinkCommandParserTest.java
  src/test/java/educonnect/storage/JsonAdaptedStudentTest.java
  src/test/java/educonnect/testutil/EditStudentDescriptorBuilder.java
  src/test/java/educonnect/testutil/StudentBuilder.java
  src/test/java/educonnect/testutil/TypicalStudents.java
Labels: bug

#97 Update ModelClassDiagram.puml and BetterModelClassDiagram.puml
  docs/DeveloperGuide.md
  docs/diagrams/BetterModelClassDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
Labels: documentation

#99 Add FindSequenceDiagram.puml
  docs/diagrams/FindSequenceDiagram.puml
Labels: documentation

#101 Remove unnecessary files uder diagrams
  README.md
  docs/diagrams/AddSequenceDiagram.png
  docs/diagrams/StudentClassDiagram.png
  docs/index.md
Labels: documentation

#104 Update tag validation regex to accept space bar
  src/main/java/educonnect/model/student/Tag.java
Labels: bug, good-to-have

#107 Update UserGuide and EditCommand message_usage
  docs/UserGuide.md
  src/main/java/educonnect/logic/commands/EditCommand.java
  src/main/java/educonnect/logic/commands/LinkCommand.java
Labels: documentation

#127 Update Application Icon to customized logo
  src/main/java/educonnect/ui/UiManager.java
  src/main/resources/images/EduConnectLogo.png
  src/main/resources/view/MainWindow.fxml
  src/test/java/educonnect/commons/util/AppUtilTest.java
Labels: nice-to-have

#126 Fix DG image bug
  docs/DeveloperGuide.md
Labels: documentation

#125 Add support to link student with URL with add command
  src/main/java/educonnect/logic/commands/AddCommand.java
  src/main/java/educonnect/logic/commands/LinkCommand.java
  src/main/java/educonnect/logic/parser/AddCommandParser.java
  src/main/java/educonnect/logic/parser/AddressBookParser.java
  src/main/java/educonnect/logic/parser/EditCommandParser.java
  src/main/java/educonnect/logic/parser/LinkCommandParser.java
  src/main/java/educonnect/model/student/Link.java
  src/main/java/educonnect/ui/HelpWindow.java
  src/test/java/educonnect/logic/commands/LinkCommandTest.java
  src/test/java/educonnect/logic/parser/LinkCommandParserTest.java
Labels: enhancement

#130 Update DG for Timetable feature
  docs/DeveloperGuide.md
Labels: documentation

#129 Update list command with option to list timetable
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/educonnect/logic/commands/CommandResult.java
  src/main/java/educonnect/logic/commands/ExitCommand.java
  src/main/java/educonnect/logic/commands/HelpCommand.java
  src/main/java/educonnect/logic/commands/ListCommand.java
  src/main/java/educonnect/logic/parser/AddressBookParser.java
  src/main/java/educonnect/logic/parser/ListCommandParser.java
  src/main/java/educonnect/ui/MainWindow.java
  src/main/java/educonnect/ui/StudentCard.java
  src/main/java/educonnect/ui/StudentListPanel.java
  src/test/java/educonnect/logic/commands/CommandResultTest.java
  src/test/java/educonnect/logic/commands/ExitCommandTest.java
  src/test/java/educonnect/logic/commands/HelpCommandTest.java
  src/test/java/educonnect/logic/parser/AddressBookParserTest.java
Labels: good-to-have

#132 Update DG on student link
  docs/DeveloperGuide.md
  docs/diagrams/StudentClassDiagram.puml
Labels: documentation
